version: '4.39'
services:
  redis:
    image: redis:8.0-M03
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: news_keycloak
    ports:
      - "8082:8080"
    command: -v start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import

volumes:
  redis_data:
  postgres_data:
  keycloak_data:
