spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        highlight_sql: true

server:
  port: 8081
#
#  application:
#    name: spring-cloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/your-repo/config-repo
#          username: your-username
#          password: your-password
