spring:
  config:
    activate:
      on-profile: ddl
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/ddl/db.changelog-1.0.sql
    default-schema: news_online