server:
  port: 8081
spring:
  docker:
    compose:
      enabled: false
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: api
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    config:
      username: catalogue_service_user
      password: password
      roles:
        - SERVICE
      fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI:http://localhost:8082/realms/news}
cache:
  #  algorithm: LRU
  max-size: 10
app:
  upload:
    path: C:\Users\user\IdeaProjects\Clevertec\news-online\manager-view\src\main\resources\static\images\
  logging:
    enabled: true
