spring:
  application:
    name: api
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      username: user
      # Ввести свой токен security. Запустить модуль config server и взять токе из консоли
      password: 87039d52-dfad-48c2-ba6c-a5c98f1dff18
      fail-fast: true
server:
  port: 8080
#  datasource:
#    url: jdbc:postgresql://localhost:5432/demo
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
#  liquibase:
#    enabled: true
cache:
  #  algorithm: LRU
  max-size: 10
app:
  logging:
    enabled: true
