server:
  port: 8888

spring:
  security:
    user:
      name: catalogue_service_user
      password: 'password'
      roles:
        - SERVICE
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ivan101454/config-repo
          default-label: master